receivers:
  otlp:
    protocols:
      http:
        endpoint: 0.0.0.0:4318
        auth:
          authenticator: basicauth

processors:
  batch:
    timeout: 5s
    send_batch_size: 256
  transform/headers:
    trace_statements:
      - context: resource
        statements:
          - set(attributes["service.name"], request["headers"]["x-service-name"]) where request["headers"]["x-service-name"] != nil
          - set(attributes["repository"], request["headers"]["x-repository"]) where request["headers"]["x-repository"] != nil
          - set(attributes["team"], request["headers"]["x-team"]) where request["headers"]["x-team"] != nil
          - set(attributes["project"], request["headers"]["x-project"]) where request["headers"]["x-project"] != nil
          - set(attributes["deployment.environment"], request["headers"]["x-environment"]) where request["headers"]["x-environment"] != nil
    log_statements:
      - context: resource
        statements:
          - set(attributes["service.name"], request["headers"]["x-service-name"]) where request["headers"]["x-service-name"] != nil
          - set(attributes["repository"], request["headers"]["x-repository"]) where request["headers"]["x-repository"] != nil
          - set(attributes["team"], request["headers"]["x-team"]) where request["headers"]["x-team"] != nil
          - set(attributes["project"], request["headers"]["x-project"]) where request["headers"]["x-project"] != nil
          - set(attributes["deployment.environment"], request["headers"]["x-environment"]) where request["headers"]["x-environment"] != nil
  resource:
    attributes:
      - key: service.namespace
        value: agent-observability
        action: upsert
      - key: deployment.environment
        value: unknown
        action: insert
      - key: service.name
        value: unknown-repo
        action: insert

exporters:
  azuremonitor:
    connection_string: ${env:AZURE_MONITOR_CONNECTION_STRING}

extensions:
  health_check:
    endpoint: 0.0.0.0:13133
  zpages:
    endpoint: 0.0.0.0:55679
  basicauth:
    htpasswd:
      file: /etc/otelcol-contrib/htpasswd

service:
  extensions: [health_check, zpages, basicauth]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [transform/headers, resource, batch]
      exporters: [azuremonitor]
    logs:
      receivers: [otlp]
      processors: [transform/headers, resource, batch]
      exporters: [azuremonitor]
