#!/usr/bin/env bash
# ==============================================================================
# setup-repo.sh — VS Code Copilot OTel per-repository setup
# ==============================================================================
#
# PURPOSE:
#   Creates a .envrc.otel file at the repo root that composes
#   OTEL_RESOURCE_ATTRIBUTES from the global piece (user.email) and the
#   repo-specific piece (repo.name). Installs a shell hook to auto-source it.
#
# WHAT IT WRITES:
#   1. <repo-root>/.envrc.otel — exports the composed OTEL_RESOURCE_ATTRIBUTES
#   2. Adds .envrc.otel to <repo-root>/.gitignore
#   3. A delimited hook block in ~/.zshrc or ~/.bashrc that auto-sources
#      .envrc.otel when you cd into the repo
#
# HOW TO UNDO:
#   Run: bash setup-repo.sh --uninstall
#   This removes the .envrc.otel file, the .gitignore entry, and the hook block.
#
# USAGE:
#   cd /path/to/your-repo
#   bash /path/to/agent-observability/scripts/otel/setup-repo.sh
#   bash /path/to/agent-observability/scripts/otel/setup-repo.sh --uninstall
#
# ==============================================================================
set -euo pipefail

readonly HOOK_START="# >>> vscode-copilot-otel repo hook >>>"
readonly HOOK_END="# <<< vscode-copilot-otel repo hook <<<"

# --- Helpers ------------------------------------------------------------------

die() {
  echo "ERROR: $*" >&2
  exit 1
}

detect_rc_file() {
  local shell_name
  shell_name="$(basename "${SHELL:-/bin/bash}")"

  case "$shell_name" in
    zsh)
      echo "${HOME}/.zshrc"
      ;;
    bash)
      if [[ -f "${HOME}/.bashrc" ]]; then
        echo "${HOME}/.bashrc"
      elif [[ -f "${HOME}/.bash_profile" ]]; then
        echo "${HOME}/.bash_profile"
      else
        echo "${HOME}/.bashrc"
      fi
      ;;
    *)
      echo "${HOME}/.bashrc"
      ;;
  esac
}

remove_hook_block() {
  local rc_file="$1"
  if [[ ! -f "$rc_file" ]]; then
    return 0
  fi
  local tmp_file
  tmp_file="$(mktemp)"
  local inside_block=0
  while IFS= read -r line || [[ -n "$line" ]]; do
    if [[ "$line" == "$HOOK_START" ]]; then
      inside_block=1
      continue
    fi
    if [[ "$line" == "$HOOK_END" ]]; then
      inside_block=0
      continue
    fi
    if [[ $inside_block -eq 0 ]]; then
      printf '%s\n' "$line" >> "$tmp_file"
    fi
  done < "$rc_file"
  mv "$tmp_file" "$rc_file"
}

add_to_gitignore() {
  local gitignore="$1"
  local entry="$2"
  if [[ -f "$gitignore" ]]; then
    if grep -qxF "$entry" "$gitignore"; then
      return 0
    fi
  fi
  echo "$entry" >> "$gitignore"
}

remove_from_gitignore() {
  local gitignore="$1"
  local entry="$2"
  if [[ ! -f "$gitignore" ]]; then
    return 0
  fi
  local tmp_file
  tmp_file="$(mktemp)"
  while IFS= read -r line || [[ -n "$line" ]]; do
    if [[ "$line" != "$entry" ]]; then
      printf '%s\n' "$line" >> "$tmp_file"
    fi
  done < "$gitignore"
  mv "$tmp_file" "$gitignore"
}

# --- Argument Parsing ---------------------------------------------------------

uninstall=0

while [[ $# -gt 0 ]]; do
  case "$1" in
    --uninstall)
      uninstall=1
      shift
      ;;
    *)
      die "Unknown argument: $1"
      ;;
  esac
done

# --- Resolve Repo -------------------------------------------------------------

if ! command -v git &>/dev/null; then
  die "git is not installed or not in PATH."
fi

repo_root="$(git rev-parse --show-toplevel 2>/dev/null)" || die "Not inside a git repository."
repo_name="$(basename "$repo_root")"
rc_file="$(detect_rc_file)"
envrc_file="${repo_root}/.envrc.otel"
gitignore_file="${repo_root}/.gitignore"

echo "Repository: $repo_name ($repo_root)"

# --- Uninstall ----------------------------------------------------------------

if [[ $uninstall -eq 1 ]]; then
  echo "Uninstalling OTel repo setup..."

  # Remove .envrc.otel
  if [[ -f "$envrc_file" ]]; then
    rm "$envrc_file"
    echo "  Removed: $envrc_file"
  fi

  # Remove from .gitignore
  remove_from_gitignore "$gitignore_file" ".envrc.otel"
  echo "  Removed .envrc.otel from .gitignore"

  # Remove hook block from rc file
  remove_hook_block "$rc_file"
  echo "  Removed hook block from $rc_file"

  echo "Done. Restart your terminal for changes to take effect."
  exit 0
fi

# --- Write .envrc.otel --------------------------------------------------------

cat > "$envrc_file" << 'ENVRC_HEADER'
# Auto-generated by scripts/otel/setup-repo.sh — do not edit
ENVRC_HEADER

cat >> "$envrc_file" << ENVRC_BODY
export OTEL_RESOURCE_ATTRIBUTES="\${OTEL_RESOURCE_ATTRIBUTES_GLOBAL:+\$OTEL_RESOURCE_ATTRIBUTES_GLOBAL,}repo.name=$repo_name"
ENVRC_BODY

echo "  Created: $envrc_file"

# --- Update .gitignore --------------------------------------------------------

add_to_gitignore "$gitignore_file" ".envrc.otel"
echo "  Added .envrc.otel to .gitignore"

# --- Install Shell Hook -------------------------------------------------------

# Remove existing hook block (idempotent)
remove_hook_block "$rc_file"

# Ensure rc file exists
touch "$rc_file"

# Append hook block
cat >> "$rc_file" << 'HOOK_BLOCK'

# >>> vscode-copilot-otel repo hook >>>
_vscode_otel_load() {
  if [[ -f "$PWD/.envrc.otel" ]]; then
    set -a; source "$PWD/.envrc.otel"; set +a
  fi
}
if [[ -n "${ZSH_VERSION:-}" ]]; then
  autoload -U add-zsh-hook
  add-zsh-hook chpwd _vscode_otel_load
elif [[ -n "${BASH_VERSION:-}" ]]; then
  PROMPT_COMMAND="_vscode_otel_load;${PROMPT_COMMAND:-}"
fi
_vscode_otel_load  # also run on shell startup
# <<< vscode-copilot-otel repo hook <<<
HOOK_BLOCK

echo "  Installed shell hook in $rc_file"
echo ""
echo "Done. To activate:"
echo "  1. cd out of and back into this repo, OR"
echo "  2. Restart your terminal"
echo "  3. Launch VS Code with 'code .' from that terminal"
