<#
.SYNOPSIS
    VS Code Copilot OTel per-repository setup (Windows PowerShell).

.DESCRIPTION
    Creates a .envrc.otel.ps1 file at the repo root that composes
    OTEL_RESOURCE_ATTRIBUTES from the global piece (user.email) and the
    repo-specific piece (repo.name). Installs a prompt hook in $PROFILE
    to auto-source it.

    WHAT IT WRITES:
      1. <repo-root>\.envrc.otel.ps1  — sets OTEL_RESOURCE_ATTRIBUTES at Process scope
      2. Adds .envrc.otel.ps1 to <repo-root>\.gitignore
      3. A delimited block in $PROFILE that dot-sources .envrc.otel.ps1 on each prompt

    HOW TO UNDO:
      .\setup-repo.ps1 -Uninstall

.PARAMETER Uninstall
    Remove the .envrc.otel.ps1 file, .gitignore entry, and $PROFILE hook block.

.EXAMPLE
    cd C:\path\to\your-repo
    & C:\path\to\agent-observability\scripts\otel\setup-repo.ps1

.EXAMPLE
    & C:\path\to\agent-observability\scripts\otel\setup-repo.ps1 -Uninstall
#>
[CmdletBinding()]
param(
    [Parameter()]
    [switch]$Uninstall
)

$ErrorActionPreference = 'Stop'

$BlockStart = '# >>> vscode-copilot-otel repo hook >>>'
$BlockEnd = '# <<< vscode-copilot-otel repo hook <<<'

# --- Helpers ------------------------------------------------------------------

function Remove-DelimitedBlock {
    param(
        [string]$FilePath
    )
    if (-not (Test-Path $FilePath)) { return }

    $lines = Get-Content -Path $FilePath -Encoding UTF8
    $result = [System.Collections.Generic.List[string]]::new()
    $insideBlock = $false

    foreach ($line in $lines) {
        if ($line -eq $BlockStart) {
            $insideBlock = $true
            continue
        }
        if ($line -eq $BlockEnd) {
            $insideBlock = $false
            continue
        }
        if (-not $insideBlock) {
            $result.Add($line)
        }
    }

    Set-Content -Path $FilePath -Value $result -Encoding UTF8
}

function Add-ToGitignore {
    param(
        [string]$GitignorePath,
        [string]$Entry
    )
    if (Test-Path $GitignorePath) {
        $content = Get-Content -Path $GitignorePath -Encoding UTF8
        if ($content -contains $Entry) { return }
    }
    Add-Content -Path $GitignorePath -Value $Entry -Encoding UTF8
}

function Remove-FromGitignore {
    param(
        [string]$GitignorePath,
        [string]$Entry
    )
    if (-not (Test-Path $GitignorePath)) { return }

    $lines = Get-Content -Path $GitignorePath -Encoding UTF8
    $filtered = $lines | Where-Object { $_ -ne $Entry }
    Set-Content -Path $GitignorePath -Value $filtered -Encoding UTF8
}

# --- Resolve Repo -------------------------------------------------------------

$gitCmd = Get-Command git -ErrorAction SilentlyContinue
if (-not $gitCmd) {
    throw "git is not installed or not in PATH."
}

$repoRoot = & git rev-parse --show-toplevel 2>$null
if (-not $repoRoot -or $LASTEXITCODE -ne 0) {
    throw "Not inside a git repository. Run this script from within a git repo."
}

# Normalize path separators for Windows
$repoRoot = $repoRoot -replace '/', '\'
$repoName = Split-Path -Leaf $repoRoot
$envrcFile = Join-Path $repoRoot '.envrc.otel.ps1'
$gitignoreFile = Join-Path $repoRoot '.gitignore'
$profilePath = $PROFILE.CurrentUserCurrentHost

Write-Host "Repository: $repoName ($repoRoot)"

# --- Uninstall ----------------------------------------------------------------

if ($Uninstall) {
    Write-Host "Uninstalling OTel repo setup..."

    if (Test-Path $envrcFile) {
        Remove-Item $envrcFile -Force
        Write-Host "  Removed: $envrcFile"
    }

    Remove-FromGitignore -GitignorePath $gitignoreFile -Entry '.envrc.otel.ps1'
    Write-Host "  Removed .envrc.otel.ps1 from .gitignore"

    if (Test-Path $profilePath) {
        Remove-DelimitedBlock -FilePath $profilePath
        Write-Host "  Removed hook block from $profilePath"
    }

    Write-Host "Done. Restart VS Code for changes to take effect."
    return
}

# --- Write .envrc.otel.ps1 ----------------------------------------------------

$envrcContent = @"
# Auto-generated by scripts/otel/setup-repo.ps1 — do not edit
`$global = [Environment]::GetEnvironmentVariable('OTEL_RESOURCE_ATTRIBUTES_GLOBAL', 'User')
`$repo = "repo.name=$repoName"
`$combined = if (`$global) { "`$global,`$repo" } else { `$repo }
[Environment]::SetEnvironmentVariable('OTEL_RESOURCE_ATTRIBUTES', `$combined, 'Process')
"@

Set-Content -Path $envrcFile -Value $envrcContent -Encoding UTF8
Write-Host "  Created: $envrcFile"

# --- Update .gitignore --------------------------------------------------------

Add-ToGitignore -GitignorePath $gitignoreFile -Entry '.envrc.otel.ps1'
Write-Host "  Added .envrc.otel.ps1 to .gitignore"

# --- Install Profile Hook -----------------------------------------------------

# Ensure profile directory and file exist
$profileDir = Split-Path -Parent $profilePath
if (-not (Test-Path $profileDir)) {
    New-Item -ItemType Directory -Path $profileDir -Force | Out-Null
}
if (-not (Test-Path $profilePath)) {
    New-Item -ItemType File -Path $profilePath -Force | Out-Null
}

# Remove existing block (idempotent)
Remove-DelimitedBlock -FilePath $profilePath

# Append hook block
$hookBlock = @"

$BlockStart
# Auto-source .envrc.otel.ps1 when the prompt renders in a repo directory
`$_vsCodeOtelOriginalPrompt = if (Test-Path Function:\prompt) { Get-Content Function:\prompt } else { `$null }
function prompt {
    `$envrcPath = Join-Path (Get-Location) '.envrc.otel.ps1'
    if (Test-Path `$envrcPath) {
        . `$envrcPath
    }
    if (`$_vsCodeOtelOriginalPrompt) {
        & ([scriptblock]::Create(`$_vsCodeOtelOriginalPrompt))
    } else {
        "PS `$(`$executionContext.SessionState.Path.CurrentLocation)> "
    }
}
$BlockEnd
"@

Add-Content -Path $profilePath -Value $hookBlock -Encoding UTF8
Write-Host "  Installed prompt hook in $profilePath"
Write-Host ""
Write-Host "Done. To activate:"
Write-Host "  1. Open a new PowerShell window, OR"
Write-Host "  2. Run: . `$PROFILE"
Write-Host "  3. Launch VS Code with 'code .' from that terminal"
